### ISSUE TITLE
pack build

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#1]
# pack build

**As a** developer **I want** to use the `pack build`command to create an image **so that** I can build my app using buildpacks,  and run it similarly to how it will run in production

## Acceptance Criteria
**Given** I have installed docker
**Given** Source code in a directory `<app-dir>`
**When** I run `pack build --dir <app-dir> --name <repo-name>:<tag-name (optional)>`
**Then** The pack cli builds an image from the source code in `<app-dir>` with the v3 buildpack lifecycle and puts it in `<repo-name>` in the local Docker daemon
**Then** I can run `docker run `<repo-name>` and see my app running

## Assumptions
1. For this first story we assume the image is fetched from and written to the docker daemon
2. We can skip `restorer` and `cacher` in this first iteration
3. We can assume the correct stack is `packs/v3` on dockerhub

**Comment by dgodd** [comment]
This is finished on `develop` branch. I am waiting on rebuilds of docker images to merge to master

**Comment by ekcasey** [comment]
Merged to master.

**Comment by ekcasey** [comment]
### Acceptance steps
1. clone `buildpack/packs`
1. int the packs repo run `v3/bin/build ubuntu:18.04 master`
1. clone `buildpack/pack`
1. in `pack` go build ./cmd/pack/`
1. `pack build -p <path-to-node-app> <image-name> 
1. `docker images` and see <image-name> in the list
1. `docker run <image-name>`
