### ISSUE TITLE
Support a zip file of an app dir with `pack build`

### ISSUE THREAD

**Issue by sclevine** [buildpack/pack#106]
**Acceptance Criteria**

_Zip file_

**Given** my application is located at the root of a zip-formatted file
**When** I run `pack build -p <path to zip> my-app`
**Then** The build succeeds

_Non-zip file_

**When** I run `pack build -p <path to file> my-app`
**Then** The build fails with a message:
```
ERROR: the provided application path must be a directory or zip-formatted file
``` 

**Notes**
- Should work regardless of file extension (check first four bytes for `PK\x03\x04`)
- Should also work for `pack run`

**Comment by ameyer-pivotal** [comment]
@nebhale Maybe we could adapt this to support jars too

**Comment by sclevine** [comment]
JARs are just zips, and the JBPs work on an exploded JAR already. This will probably just work. This is actually how the cf CLI works today.

**Comment by ameyer-pivotal** [comment]
@sclevine I think pack only supports directories currently though. I agree if it will work for zips it will work for jars (as long as we allow the extension).

**Comment by nebhale** [comment]
I'd give serious thought to not using extension but rather looking for the magic number (`PK\x03\x04`) instead as the file extension for Java-archives are all over the place.  At first thought I know of `.jar`, `.war`, `.ear`, `.rar`, `.apk`, `.par`, and `.kar`.

**Comment by ameyer-pivotal** [comment]
@nebhale That makes sense. I was hoping that we could do something like that. Thanks for the clarification.

**Comment by mgibson1121** [comment]
This story passes acceptance.
