### ISSUE TITLE
Use a hashed buildpack id/version for dir/file names

### ISSUE THREAD

**Issue by jkutner** [buildpack/pack#113]
When creating a temp file or directory that is unique to a given buildpack id/version, we should not name it with the raw strings (since they could be invalid file/dir names, or even open us to a directory traversal attack). Instead we should always hash them with something like:

```
h := sha1.New()
io.WriteString(h, buildpackId)
sha := h.Sum(nil)
```

See #112

**Comment by ekcasey** [comment]
I think is resolved. Let me know if you find any that slipped through the cracks.
