### ISSUE TITLE
No Way to Ignore Launch Layers

### ISSUE THREAD

**Issue by nebhale** [buildpack/pack#124]
Currently, when building an application for the second time, you can use the `--clear-cache` flag to ignore any previous layer that was marked `cache = true`.  However, there is no way to cause a build to ignore previous layer marked `launch = true`.  Therefore, in a registry that doesn't allow images/tags to be deleted (e.g. `registry:latest`), there is no way to ever force that layer to be recreated short of destroying the entire registry.

There needs to be a way to cause launch layers to be ignored even if they exist.  I'd argue that `--clear-cache` implies this to the average user (rather than our strictly correct current implementation) but I would settle for another flag.

**Comment by ekcasey** [comment]
fixed in `v0.1.0`
