### ISSUE TITLE
Path to access the fixtures within the README file is not correct

### ISSUE THREAD

**Issue by cmoulliard** [buildpack/pack#13]
This command defined within the README file is not correct 

```
./pack build myorg/myapp -p fixtures/node_app --detect-image packsdev/v3:detect --publish
```

and should include `accetpance folder` : 

```
./pack build myorg/myapp -p acceptance/fixtures/node_app --detect-image packsdev/v3:detect --publish
```

**Comment by sclevine** [comment]
Thanks for the contribution @cmoulliard!

We may have to leave this open for a little while as our CLA process/bot isn't quite ready yet. Apologies for the delay.

**Comment by jchesterpivotal** [comment]
I've closed the relevant PR because the README and code had drifted far enough forward that it wasn't correct any more.

In our current README we don't use the fixture node app (now `acceptance/testdata/node_app`) at all. Should we?

**Comment by dgodd** [comment]
@cmoulliard We are closing this becuse as @jchesterpivotal says above the README has now been changed
