### ISSUE TITLE
`pack build` should check the run image's stack ID when `--run-image` is specified

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#134]
**Given** I have a builder `my-builder` with stack ID `some.stack` and a run image `my-run-image` with stack ID `other.stack`
**When** I run `pack build my-image --builder my-builder --run-image my-run-image`
**Then** I see an error informing me that the run image is invalid b/c the stack does match the builder

**Given** I have a builder `my-builder` with stack ID `some.stack` and a run image `my-run-image` with stack ID `some.stack`
**When** I run `pack build my-image --builder my-builder --run-image my-run-image`
**Then** It succeeds

**Comment by mgibson1121** [comment]
Any tips for how to accept this?  Ran `pack build testingrunimage --run-image cfbuildpacks/cflinuxfs3-cnb-experimental:run` but couldn't find `stack ID` in the lifecycle output

**Comment by ekcasey** [comment]
@mgibson1121 Apologies, I added some acceptance criteria. It would have been ideal to have the ACs before we finished the issue, but we ended up fixing this bug as a side effect of https://github.com/buildpack/pack/issues/158 so I just moved it over to done.

**Comment by mgibson1121** [comment]
This story is accepted

**Comment by ekcasey** [comment]
fixed on `master`, will ship in `v0.2.0`
