### ISSUE TITLE
`pack set-default-builder` should check if builder exists and issue a warning if not

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpack/pack#135]
Check remotely and locally perhaps?

**Comment by matthewmcnew** [comment]
It would also be useful to check to make sure the image is a valid builder.

For example:
```
pack set-default-builder java
```

Should look at the library/java metadata and verify that it is not all a real builder.

**Comment by ameyer-pivotal** [comment]
@matthewmcnew I love this idea. Users need some immediate feedback about whether they chose a valid builder!

**Comment by mgibson1121** [comment]
@ameyer-pivotal Checked this out, seems to error out if the builder doesn't exist.  The title of the ticket suggests pack should issue a 'warning' if the builder doesn't exist.  To me this would imply issuing a warning and then asking the user if they're certain they want to proceed.  @ekcasey or @sclevine Can you guys speak to the desired functionality?  I'm ok with how it's currently implemented but want to make sure.

**Comment by ameyer-pivotal** [comment]
@mgibson1121 I had posed this question earlier and forgot to update the title:

> I wonder if it should be an error in both cases (non-existence, invalid) rather than a warning... Do we really want to allow users to put themselves in a potentially confusing spot?

cc: @ekcasey

**Comment by mgibson1121** [comment]
@ameyer-pivotal I'd rather see functionality that validates builders sooner rather than later.  Accepting.
