### ISSUE TITLE
`set-default-builder` should suggest builders

### ISSUE THREAD

**Issue by djoyahoy** [buildpack/pack#137]
If I run `set-default-builder` with the help flag, or without providing a builder, I'd like a hint at which builders I could potentially use. Whether we display that in the help text, or from another command specific to list suggested builder, that information would be useful for users who already know they need to set a default builder but don't know what builders are available.

**Comment by jromero** [comment]
I gave this a fair try but ended up having a slew of issues trying to get it into the `--help` output so created the PR to only include it when builder name is not provided.

1. cobra doesn't call `PersistentPreRun` for --help, probably with good reason making the logger remain uninitialized. I could have created a new one but that defeats the purpose of DI. The other option was to create a "default" logger until the properly set one was initialized but again didn't really think that idea was ideal.
2. The default help text (aka template) is constructed by private cobra methods. I worked around this by holding a reference to the original `HelpFunc` and calling it inside the custom `HelpFunc` but that just felt wrong.

Ultimately, I propose that we don't cram it in `--help` but instead add another command. For example, `list-builders` which for now simply suggests builders but in the future could be provided centrally from a server. In the meantime, builders to that list could be added via PR.

**Comment by ekcasey** [comment]
@jromero I agree that a separate command to list the suggested builders is a good idea. I would propose `suggest-builders` instead of `list-builders`. I worry that if a user runs `create-builder` followed by `list-builders` and doesn't see their builder in the list, that could be confusing. `suggest-builders` implies that the list is not comprehensive
