### ISSUE TITLE
Windows build shows control characters

### ISSUE THREAD

**Issue by dariusj18** [buildpack/pack#141]
Version: v0.1.0 (git sha: e1793ab9fc3d172a416183ef3df20daf089eba19) 

> [90m[0mv0.1.0 (git sha: e1793ab9fc3d172a416183ef3df20daf089eba19)

OS: Windows 10, Command line and powershell

This is in no-color mode

> [1B46f3b1a1: Pulling fs layer
> [1B6dfa0a50: Pulling fs layer
> [1B4cd74a92: Pulling fs layer
> [1Bee0f8701: Pulling fs layer
> [1Be1f13abc: Pulling fs layer
> [1B8a4a7fc2: Pulling fs layer
> [1Bbd860b03: Pulling fs layer
> [1B0b3e8890: Pulling fs layer
> [1Bbcae724a: Pulling fs layer
> [1B2c869c4b: Pulling fs layer
> [1Bf3273474: Pulling fs layer
> [1Bc3d3c281: Pulling fs layer
> [1B555af390: Pulling fs layer
> [1B10427aaa: Pulling fs layer
> [1Ba9e0be09: Pulling fs layer
> [1B504fc59e: Pulling fs layer
> [1B59fc4b3a: Pulling fs layer
> [1B1424f9de: Pulling fs layer
> [1Baa7755cc: Pulling fs layer
> [1B39aec42b: Pulling fs layer
> [1B2268f1ca: Pulling fs layer
> [1Bda89c790: Pulling fs layer
> [1B29f2867c: Pulling fs layer
> [1B1ee3ddf3: Pulling fs layer
> [1BDigest: sha256:fa15f5b8a651b88e84c0b4fa28177fc9195ec6d2b0d14c43cfa877c1ffc083fe317B/317B9MBB
> Status: Downloaded newer image for heroku/buildpacks:latest
> Selected run image 'heroku/pack:18' from builder 'heroku/buildpacks'
> Pulling run image 'heroku/pack:18' (use --no-pull flag to skip this step)
> 18: Pulling from heroku/pack

It's much worse in color mode

> m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94cdd60b3e8890: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                                    ]  59.55MB/212.6MBedb41424f9de: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                      ]  6.724MB/1cdd60b3e8890: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                                    ]   60.1MB/212.6MBedb41424f9de: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                      ]   6.86MB/1d58a8a4a7fc2: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                        cdd60b3e8890: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                                    ]  60.64MB/212.6MBedb41424f9de: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                     ]  cdd60b3e8890: [94mDownloading[0m [[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m=[0m[94m>[0m                                    ]  61.18MB/212.6MB[18B[90m[0m[31;1mERROR: [0mcontext canceled

**Comment by ericis** [comment]
We have the same configuration... This also shows on the Git bash (plus cmd and ps)
