### ISSUE TITLE
pack users can view suggested builders

### ISSUE THREAD

**Issue by mgibson1121** [buildpack/pack#144]
As a pack cli user
I want the option to reference builders suggested for use by the CNB project
So that I can feel confident about the builder I use when I run ```pack set-default-builder```

**Acceptance Criteria**

_Given_
I have saved the pack binary in an executable path

**Case 1:**  _Display list of suggested builders_

**When** I run ```pack suggest-builders``` 
**Then** I see the list of suggested buildpacks I would see if I tried to run pack build for the first time w/o setting a default-builder

**Case 2:**   ```pack suggest-builders``` _appears in "help" output_

**When** I run ```pack``` 
**Or** ```pack --help```
**Then** I see ```pack suggest-builders``` included in the  list of commands
**And** the associated text reads ```Display list of builders recommended by the Cloud Native Buildpacks project```

**Notes:**

* I don't think users need to be able to run --help on ```pack suggest-builders``` because the text they see in the initial help output should be sufficient for them to understand the purpose of the command

**Comment by ekcasey** [comment]
@mgibson1121 can I change it to `suggest-builders`?

**Comment by jromero** [comment]
I was talking to @ameyer-pivotal about this yesterday and I personally think a `list-builders` command would be a better solution all around IF we could get a list of the local builder images from the docker daemon. Based on a quick Google search, this should be doable.

This idea was derived from @ekcasey's comment: https://github.com/buildpack/pack/issues/137#issuecomment-479476573

If `list-builders` can be done to satisfy the use case of _"I just created a builder via `pack create-builder`. What was it again?"_, then I think adding the suggested builders to that output would also be ideal. Making the need for a `suggested-builders` command moot.

The proposed output being something like:

```
pack list-builders

Local Builders:

    * my/custombuilder1
    * my/custombuilder2

Suggested Remote Builders:

    * cloudfoundry/cnb:bionic             small base image with Java & Node.js
    * cloudfoundry/cnb:cflinuxfs3         larger base image with Java, Node.js & Python
    * heroku/buildpacks                   heroku-18 base image with official Heroku buildpacks
```

This would help two-fold...

1. Give the user a list of builders they've created via `create-builder` command
2. Discoverability - As a new user, I would see them running this command to see what builders are available hence we provide the suggested builders.

**Comment by mgibson1121** [comment]
@jromero I'm most concerned with making the list of recommended remote builders easily and clearly accessible to new users.  To me, I see two separate stories.  One is getting a quick win and putting in some kind of command that shows the suggested remote builders (@ekcasey I'm fine with calling it ```suggest builders```).  Another is telling the user which builders they have locally.  I think the two commands have different use cases and appeal to users with different levels of knowledge about CNBs.  There also seems to be a degree of technical uncertainty as to how we would implement displaying a list of local builders, so I propose we implement the commands separately, use it for a while, and then consider merging them together as @jromero outlines above.

**Comment by ameyer-pivotal** [comment]
@mgibson1121 I could be convinced that they are two stories, but I definitely think that they belong in the same command. Perhaps if we added the local builder listing functionality, then we change the name (though I would rather do it all before a release, so we don't swap a command on users).

**Comment by mgibson1121** [comment]
@jromero Thanks for your contributions on the subject.  After talking this through with the CNB team, we're going to first implement ```suggest-builder``` and then consider a command that lists local builders separately.  This is largely due to the UX and technical uncertainty posed by how to reconcile builders that the user built and published with the output of a ```list-builders``` type command.  

We'll continue to think about the topic and use the card you opened (#148) to track this work.

**Comment by ameyer-pivotal** [comment]
@jromero To add to what @mgibson1121 said, when creating a builder with the `--publish` command, the builder is created purely remotely and no local builder will exist. That's the main wrench in the machine to think about with this.

**Comment by jromero** [comment]
@mgibson1121 / @ameyer-pivotal Sounds good to me! Definitely not trying to stir the pot. Just wanted to contribute to the topic and show what was possible as an exercise for myself.

**Comment by mgibson1121** [comment]
This story passes acceptance
