### ISSUE TITLE
Existing images built with older pack version can cause layering issues

### ISSUE THREAD

**Issue by trisberg** [buildpack/pack#145]
I've had two recent builds with the riff buildpack fail when there were existing images built with older versions of pack. The versiona of pack used by riff are:

```
	github.com/buildpack/pack v0.1.0
```

Case #1:
```
$ kubectl logs square-test-4zdqz-deployment-b8fb9f94-rkz9z -c user-container
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/layers/io.projectriff.node/riff-invoker-node/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```
Full build log is here: https://github.com/projectriff/riff/issues/1207#issuecomment-479960739

Case #2:
```
===> EXPORTING
[exporter] adding layer 'app' with diffID 'sha256:9faa808ac52929cad20ca7d872aad9088d5d82aa02709d236a8bc0b07648e6db'
[exporter] adding layer 'config' with diffID 'sha256:cf44337980f6134288892bb30effa9049e9c54a409ebbca9cc978fbc83ca6269'
[exporter] adding layer 'launcher' with diffID 'sha256:7417c05f2e27d60b777911b95a538f0bac23fec8fec4175a499039949781fabc'
[exporter] Error: failed to : layer 'org.cloudfoundry.buildpacks.nodejs:node' is cache=true but has no contents

Error: failed with status code: 7
```

Full build log is here: https://github.com/projectriff/riff/issues/1207#issuecomment-478680063

**Comment by ekcasey** [comment]
@trisberg because the caching mechanism is completely different between pack v0.0.9 and v0.1.0 you would need `pack build` with `--clear-cache` to get a clean slate. A cache from a `pack v0.0.9` build will not be usable with `pack v0.1.0`.

Also worth noting, lifecycle v0.1.0 is not compatible with pre `v0.1.0` version of pack or with the knative template (yet!). Lifecycle v0.2.0 (with support for volume caching) and a compatible knative template are the next top priority.

**Comment by ekcasey** [comment]
I am going to close this. Now that we have released the beta there should be fewer breaking changes like this one going forward. Feel free to reopen if you still have questions or if `--clear-cache` didn't fix the issue for you.
