### ISSUE TITLE
[non-issue] this project is well documented, thank you

### ISSUE THREAD

**Issue by aegershman** [buildpack/pack#147]
Not an issue. Just wanted to say I love how well-documented this project is-- and by that I mean the doc is quality, not a massive tomb. The examples are straightforward and consumable, the background explanations are approachable and not barfing too much info at you, and overall the `README.md` landing page is concise but not lacking important details.

That's all, just wanted to say thanks to everyone involved && especially thanks to those who put care into the doc 👍

**Comment by ekcasey** [comment]
thanks so much for the feedback!

**Comment by jkutner** [comment]
yay @ameyer-pivotal!!
