### ISSUE TITLE
Validate run-image in builder.toml

### ISSUE THREAD

**Issue by mgibson1121** [buildpack/pack#155]
As a user configuring a builder.toml file
I want pack to run validation on the `run-image` I specify
So that I don't end up creating a useless or confusing builder

**Given** I have configured a builder.toml file that is valid except for the run-image field

_Case 1:_ Specified run-image or run image mirror stack ID does not match build image stack ID

**When** I run `pack create-builder somebuilder -b builder.toml`
**Then** I see `Error: image 'whatever_I_named_the_run_image' stack 'XXX' does not match requested stack 'YYY'`

_Case 2:_ Specified run-image or run image mirror cannot be found on the Internet

**When**  I run `pack create-builder somebuilder -b builder.toml --publish`
**Then** I see an  `Warning:  image 'whatever_I_named_the_run_image' not accessible` for each inaccessible image

**Comment by mgibson1121** [comment]
This story passes acceptance

**Comment by ekcasey** [comment]
will ship in `v0.2.0`
