### ISSUE TITLE
Generate dockerfile 

### ISSUE THREAD

**Issue by aamorozov** [buildpack/pack#162]
Hi! When running `pack build <image-name>` to generate a docker image, is there a way to generate a local Dockerfile, in case I would want to tweak something in auto-generated file? Thanks!

Ps. I've just started using the tool and might be missing something, but couldn't find it in the issues/documentation.

**Comment by jkutner** [comment]
No, there isn't a generated Dockerfile, but you can use the generated image in a Dockerfile like any other Docker image. For example:

```
$ pack build myapp
```

Then

```Dockerfile
FROM myapp
RUN ...
```

**Comment by sclevine** [comment]
For more context: `pack` uses the lifecycle to generate images directly, without using Dockerfiles. This allows us to manipulate image layers arbitrarily for better performance, but it means that there is no equivalent Dockerfile that we could output.

**Comment by aamorozov** [comment]
Thank you!
