### ISSUE TITLE
As a developer, I can use pack with an HTTP proxy

### ISSUE THREAD

**Issue by sclevine** [buildpack/pack#169]
Very important for enterprise/corporate use cases.

**When** I set the `HTTP_PROXY`, `HTTPS_PROXY`, and/or `NO_PROXY` environment variables 
**And** I run `pack build`
**Then** All connections from the pack CLI and associated containers are routed through the specified proxies.

**Notes**
- How should we deal with Docker's configuration of these env vars (via config.json)? Docker will inject the env vars itself in some cases, and transparently proxy in other cases.
- https://github.com/moby/moby/blob/28d7dba41d0c0d9c7f0dafcc79d3c59f2b3f5dc3/client/client.go
- https://github.com/cloudfoundry-incubator/cflocal/issues/14
- Best idea is to inject them directly from the CLI environment, ignore values in config.json

**Comment by sweeneyb** [comment]
I just hit this and would volunteer to help test once there's a patch.  Here's the error in case somebody comes looking:
`$ /tmp/pack build brian:foo
Defaulting app directory to current working directory /vagrant/projects/foo-service (use --path to override)
Using default builder image cloudfoundry/cnb:bionic
Pulling builder image cloudfoundry/cnb:bionic (use --no-pull flag to skip this step)
bionic: Pulling from cloudfoundry/cnb
Digest: sha256:175798db658a45eb6b4e707a8fde2779567650dc93544a4322036762ee463d78
Status: Image is up to date for cloudfoundry/cnb:bionic
Selected run image packs/run:0.1.0 from builder cloudfoundry/cnb:bionic
Pulling run image packs/run:0.1.0 (use --no-pull flag to skip this step)
0.1.0: Pulling from packs/run
Digest: sha256:99dee5262498d21b302321fd5d7b889c1685bfbd0ea12a64f786d91232e52278
Status: Image is up to date for packs/run:0.1.0
Using cache image pack-cache-6ffd32cfc585
===> DETECTING
[detector] Trying group of 8...
[detector] ======== Results ========
[detector] Cloud Foundry OpenJDK Buildpack: pass
[detector] Cloud Foundry Build System Buildpack: pass
[detector] Cloud Foundry JVM Application Buildpack: pass
[detector] Cloud Foundry Azure Application Insights Buildpack: skip
[detector] Cloud Foundry Debug Buildpack: skip
[detector] Cloud Foundry Google Stackdriver Buildpack: skip
[detector] Cloud Foundry JMX Buildpack: skip
[detector] Cloud Foundry Procfile Buildpack: skip
===> RESTORING
[restorer] cache image 'pack-cache-6ffd32cfc585' not found, nothing to restore
===> ANALYZING
[analyzer] WARNING: image 'brian:foo' not found or requires authentication to access
[analyzer] WARNING: image 'brian:foo' has incompatible 'io.buildpacks.lifecycle.metadata' label
===> BUILDING
[builder] -----> Cloud Foundry OpenJDK Buildpack 1.0.0-M6
[builder] -----> OpenJDK JDK 11.0.2: Contributing to layer
[builder]        Downloading from https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64/openjdk-11.0.2_09.tar.gz
[builder] Get https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64/openjdk-11.0.2_09.tar.gz: dial tcp 13.249.87.18:443: connect: connection refused

[builder] Error: failed to : exit status 103
ERROR: failed with status code: 7


But I can reach this normally:
$ curl -I https://java-buildpack.cloudfoundry.org/openjdk-jdk/bionic/x86_64/openjdk-11.0.2_09.tar.gz
HTTP/1.1 200 Connection established
Server: SimpleHTTP/0.6 Python/3.6.4
Date: Fri, 03 May 2019 13:42:10 GMT
Proxy-Agent: SimpleHTTP/0.6 Python/3.6.4

HTTP/1.1 200 OK
Content-Type: application/x-tar
Content-Length: 194941827
Connection: keep-alive
Date: Fri, 03 May 2019 13:37:09 GMT
Last-Modified: Sat, 06 Apr 2019 01:20:37 GMT
ETag: "3b177f31fb374efa752329644c5c8afa"
x-amz-version-id: gltRlwCgyBpPiFdddojQE2zt3seosxS0
Accept-Ranges: bytes
Server: AmazonS3
Age: 303
X-Cache: Hit from cloudfront
Via: 1.1 5764c2906825a6dd0688f4b549ef2cdf.cloudfront.net (CloudFront)
X-Amz-Cf-Id: E0J4WO6KOxHvydO9RwMvKoaDeZHzcqq9aU0JrBW8EerZcJ1GskoJ7A==`

**Comment by ekcasey** [comment]
@sclevine It's much easier to implement this story if we don't support the case where the proxy is running on the host machine (it's possible but more laborious). Given that the motivation for this story is to support enterprise/corporate use cases, the vast majority of which involve an external proxy, we were thinking we should ship the quick version (w/o local proxy support), and address local proxies in another issue.

**Comment by sclevine** [comment]
👍

**Comment by mgibson1121** [comment]
Needs @sclevine because I don't know where I would set env variables.  If the following is provided:

1) Where a user would configure an environment variable
2) The syntax in which they would be configured
3) How to tell if `all connections from the pack CLI and associated containers are routed through the specified proxies`

I could probably accept it.

**Comment by ekcasey** [comment]
done on `master`, will ship in `v0.2.0`
