### ISSUE TITLE
Add description to builder config

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#172]
### `inspect-builder`
**Given** I run `pack create-builder my-builder -b builder.toml` with the following field in the `builder.toml` file
```
description = "A short description of my builder"
```
**When** I run `pack inspect-builder my-builder` then I observe the following field in the output
```
Desciption: A short description of my builder
```

### `suggest-builders` w/ description
**Given** a suggested builder has been created with a description
**When** I run `pack suggest-builders`
**Then** The desciption field in the output will be populated with the configured description

### `suggest-builders` w/o description (Backwards Compatibility)
**Given** a suggested builder has an empty description
**When** I run `pack suggest-builders`
**Then** The current hard-coded description will be printed

**Comment by mgibson1121** [comment]
@ameyer-pivotal  Validated cases 1 and 3, but don't know how to modify the suggested builders.  Would I just docker pull them, add a description, and then run `pack create-builder`?  I also don't want to mess with them as they are the "canonical" builders.

**Comment by ameyer-pivotal** [comment]
That's a good point... @sclevine @ekcasey Are y'all OK deferring part 2 acceptance and just validating it when we create new builders? It only looks at remote builders and we don't want to mess with the published ones just yet.

**Comment by mgibson1121** [comment]
This story is accepted

**Comment by ekcasey** [comment]
done on `master`, will ship in `v0.2.0`
