### ISSUE TITLE
Improve performance when creating daemon images

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#178]
**Given** my builder has version `0.2.0` of the lifecycle or higher
**When** I run `pack build`
**Then** a cache volume  is used by `cacher` and `restorer` (rather than the current cache-image)

**Given** my builder has version `0.2.0` of the lifecycle or higher
**When** I run `pack build` without the `--publish` flags
**Then** The exporter is run with the `-launch-cache` option and layers are cached in directory named `launch` in a cache volume

**Given** my builder has version `0.1.0` of the lifecycle or an unknown version
**When** I run `pack build`
**Then** the current behavior is unchanged (an image is used for caching and the exporter is not passed the `-launch-cache` flag)

Notes:
Eventually we will want to change the behavior of "unknown" lifecycles to match the `v0.2.0` behavior, once all of our suggested builders have migrated to the new lifecycle version

**Comment by ameyer-pivotal** [comment]
@ekcasey What about `0.2.0` + a true `--publish`? Should we use the volume cache still?

I'm thinking through the logic like this:

`0.2.0` or higher ==> always use volume cache

`0.2.0` or higher + daemon (i.e. `--publish == false`) ==> use `launch-cache`

**Comment by ekcasey** [comment]
You are right, the choice to use volume cache during `cacher/resotrer` phases should be totally independent of the `--publish` flag. I'll update the issue.

**Comment by ekcasey** [comment]
done on `master` will ship in `v0.2.0`
