### ISSUE TITLE
Avoid losing executable bit in app files when building on windows

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#180]
### Problem Statement

Right now, if a user runs `pack build -p <app-dir>` on a windows host, NONE of the files copied into the build container from the `<app-dir>` will be executable. Given that some files will need to be executable for certain buildpacks to succeed (e.g. `mvnw`) this causes failures.

### Suggested Workaround

Make everything in the app dir executable (!) when copying the app into the `/workspace` volume.

### Prior Art

Cloud Foundry currently does this when a user `cf push`es app code from a windows machine.

**Comment by jromero** [comment]
**Passes Acceptance**

Verified that files in resulting app image are executable when built on Windows.
