### ISSUE TITLE
Document the requirements of a stack

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#191]
Requirements:

Labels:
* `io.buildpacks.stack.metadata` OR `io.buildpacks.stack.id`

Env Vars:
* `CNB_USER_ID`
* `CNB_GROUP_ID`
* `CNB_STACK_ID`

Implementation Suggestions:
* Add a new sections to the docs website
* Link from the buildpack/stacks repo

**Comment by ameyer-pivotal** [comment]
@ekcasey @sclevine I don't see any reference to `io.buildpacks.stack.metadata` in our code. Am I missing something?

**Comment by ekcasey** [comment]
@ameyer-pivotal This was originally intended to be played after https://github.com/buildpack/pack/issues/179 which introduces this label. We can just document it as is and update the documentation when we introduce the new label.

**Comment by ameyer-pivotal** [comment]
Started this, but ended up setting it down due to other priorities. Work can be picked up on branch: `wip-custom-stacks`.
