### ISSUE TITLE
De-duplicate pack docs

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpack/pack#205]
- Point to buildpacks.io from readme instead of duplicating docs in repo (for docs in readme and app journey tutorial)

- Create a docs site branch for bleeding edge docs (corresponding to master)

- Possibly: look into best way to host old/multiple versions of the docs simultaneously

**Comment by ameyer-pivotal** [comment]
Researched multiple versions. Findings:

- Using `keep_history` = true and publishing branches to their own directories doesn't work (the `gh-pages` branch can't work with sister directories, as GH looks for an index.html at the top-level). It seems multipe subdirs within master (and hence in the rendered `gh-pages` branch) for each version of docs is recommended.

- A tool called [gh-pages-multi](https://github.com/koumoul-dev/gh-pages-multi) may do the subdir work for us on `gh-pages` branch without us needing to maintain the subdirs on master.

**Comment by ameyer-pivotal** [comment]
Created a branch called `edge` to track pending docs changes (corresponding to `pack` master). Upon each release, we'll stage a PR from `edge` -> `master` (keeping `edge` for further use in the next release).

**Comment by mgibson1121** [comment]
@ameyer-pivotal Did you mean to hyperlink to buildpacks.io here?  It's just plain text.
![Screen Shot 2019-07-12 at 10 09 24 AM](https://user-images.githubusercontent.com/18624859/61134281-4c5cb980-a48d-11e9-91e3-1313d8f40092.png)

**Comment by ameyer-pivotal** [comment]
@mgibson1121 Sorry, the AC's should have been clearer in that we need to link to the website from the `pack` repo, not necessarily `docs`.

**Comment by ameyer-pivotal** [comment]
@mgibson1121 Updated it on the `docs` repo too for good measure ;)
