### ISSUE TITLE
How do you create a builder in a CI?

### ISSUE THREAD

**Issue by poy** [buildpack/pack#209]
According to the README, `pack` is intended for
> Buildpack authors to develop and package buildpacks for distribution.

However, pack also requires the `docker` CLI. This implies it won't easily fit into a CI. So what is the correct way for a buildpacks developer to create (via automation) buildpack builders?

**Comment by sclevine** [comment]
The pack CLI only requires a Docker daemon for two things:

1. To run containers during `pack build`. (And this is only because macOS and Windows systems don’t natively support Linux containers. To build app images in CI, you can use the lifecycle directly in unprivileged containers provided by your platform.)

2. To store images when you don’t pass `--publish` to any command that generates an image.

So `pack create-builder --publish` does not require a Docker daemon. We should definitely document this clearly.

**Comment by poy** [comment]
Awesome thanks!

**Comment by poy** [comment]
So it seems like `pack` still requires `docker` even when publishing. I created a docker container with `pack` that tried to publish to gcr.io, however I got the following error:

```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by sclevine** [comment]
That’s very surprising. While `pack build --publish` requires a Docker daemon (because running buildpack code always requires a container), `pack create-builder --publish` should not.

Could you provide the command you executed and all of the output?

**Comment by poy** [comment]
I created a BuildTemplate (knative) that uses an image with `pack` installed. It then does the following command:

``` 
pack create-builder --publish --builder-config=/workspace/builder.toml ${IMAGE}
```

The build fails. The logs are:

```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by poy** [comment]
OK, I've made some progress on this. It works as you say if I build `pack` from `master`. However version `.0.2.1` does not.

**Comment by ekcasey** [comment]
@poy this looks like a bug to me, even on master, introduced with the run-image validation in v0.2.0.

I think this PR should provide the fix https://github.com/buildpack/pack/pull/213

**Comment by poy** [comment]
@ekcasey Sounds good. One thing to note, it did work with master.

**Comment by ekcasey** [comment]
@poy we hope to ship pack v0.3.0 in approximately one week

**Comment by ekcasey** [comment]
I am going to close this given that the bug is fixed on master, feel free to reopen @poy if you have any additional questions
