### ISSUE TITLE
automatically name latest build from commit sha

### ISSUE THREAD

**Issue by sclevine** [buildpack/pack#21]
**Deliverables**
Each push to github should generate three binaries:
- `pack-[7-char-sha]-macos`
- `pack-[7-char-sha]-linux`
- `pack-[7-char-sha]-windows`

These binaries should be publicly hosted in a google cloud bucket with a dedicated account for this joint effort.

**Comment by dgodd** [comment]
@sclevine currently the travis build number is used. Do you really want the sha instead?

**Comment by sclevine** [comment]
no opinion

**Comment by dgodd** [comment]
@ssisil I suggest we close this issue
