### ISSUE TITLE
Expose functions to load builder config files

### ISSUE THREAD

**Issue by scothis** [buildpack/pack#214]
The logic necessary to load config files is locked up with the CLI commands and is not usable by the API client. For example, to create a builder it is necessary to have a BuilderConfig which for the CLI is defined in a builder.toml file. There is processing the CLI does on the toml file after it is parsed in order to make the file usable. This [logic is locked in unexpected methods](https://github.com/buildpack/pack/blob/b914032c63f6927813f2accb523cf584ea25a556/commands/create_builder.go#L62-L103) exposed only to the CLI commands.

I'd like to be able to use the API to create a builder from a builder.toml without needing to install the CLI (see https://github.com/projectriff/builder/issues/46)

**Comment by ekcasey** [comment]
@scothis This is a very reasonable request. We can prioritize this.

**Comment by ameyer-pivotal** [comment]
@scothis PR #227 is up to address this. Feel free to take a look and comment.
