### ISSUE TITLE
Downloading during pack create-builder is unfriendly

### ISSUE THREAD

**Issue by dsyer** [buildpack/pack#216]
When I run `pack create-builder` (e.g. from here: https://github.com/projectriff/builder) it downloads a ton of stuff. While it is downloading there is no feedback from the process, and it can take a really long time. Worse, the process is not interruptible (^C doesn't work), and I have to find the pid and kill it manually if I want to bail out.

**Comment by ekcasey** [comment]
Thanks for the feedback. I split your request into two separate issues so we can prioritize them independently:

Interrupting downloads - https://github.com/buildpack/pack/issues/236
Displaying progress - https://github.com/buildpack/pack/issues/236

I am going to close this but feel free to reopen or comment on the new issues if they don't fully capture the scope of your feedback.
