### ISSUE TITLE
Allow --path argument to point at artifact in addition to directory

### ISSUE THREAD

**Issue by nebhale** [buildpack/pack#220]
Currently, the `--path` argument only allows arguments that are directories.  In the Java world, it's very common to have a single artifact (e.g. `myapp.jar`) and this restriction on a directory only is too restrictive.

The `--path` argument should allow individual files and either put that file as a single item within the application directory or expand the file into the application directory if it is an archive.

**Comment by ameyer-pivotal** [comment]
Duplicate of #106. We'll continue conversation there.
