### ISSUE TITLE
How to combine buildpacks from builder and local file system?

### ISSUE THREAD

**Issue by jsamoocha** [buildpack/pack#223]
I'm trying to build an image using the `heroku/python` and `heroku-community/apt` buildpacks. The first is included in the `heroku/buildpacks` builder (which I set as default builder). I git-cloned the second to a local path.

When trying `pack build [NAME]:[TAG] --buildpack [LOCAL_PATH_TO_heroku-buildpack-apt] --buildpack heroku/python`, build fails as follows:

```
Using default builder image heroku/buildpacks
Pulling image index.docker.io/heroku/buildpacks:latest
latest: Pulling from heroku/buildpacks
Digest: sha256:ebe9cac86cf5aff48e18e085d02ab259d188446c57d211b74eb2ae5e0a81827d
Status: Image is up to date for heroku/buildpacks:latest
Selected run image heroku/pack:18 from builder
Pulling image heroku/pack:18
18: Pulling from heroku/pack
Digest: sha256:ed100d5a3005613e368b97c41eb6e1b6b42aef361de7056ae836176965d98326
Status: Image is up to date for heroku/pack:18
No version for [LOCAL_PATH_TO_heroku-buildpack-apt] buildpack provided, will use [LOCAL_PATH_TO_heroku-buildpack-apt]@latest
No version for heroku/python buildpack provided, will use heroku/python@latest
setting custom order

ERROR: failed to set custom buildpack order: no versions of buildpack [LOCAL_PATH_TO_heroku-buildpack-apt] were found on the builder
```

where `[LOCAL_PATH_TO_heroku-buildpack-apt]` is an absolute path.

Obviously, the custom buildpack `heroku-buildpack-apt` is not in the builder. How can I specify that this buildpack is on the local file system?

**Comment by jromero** [comment]
What version of `pack` are you running? If you are using the latest released version then the associated code to differentiate between a directory and an image name is [here](https://github.com/buildpack/pack/blob/v0.2.1/build.go#L260). This has further been improved in [master](https://github.com/buildpack/pack/blob/master/build.go#L260).

Either implementations would use the [requirement for buildpacks to have a buildpack.toml](https://github.com/buildpack/spec/blob/master/buildpack.md#buildpack-package), along with other strategies, to determine if it's a local compatible buildpack. This file is missing from [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt) making it incompatible. Maybe @jkutner or @hone can provide some more insight here.

**Comment by jsamoocha** [comment]
Pack version is v0.2.1. Thanks for pointing to the relevant docs and code - it made me realize my mistake, i.e. confusing Cloud Native buildpacks with Heroku buildpacks.

As you suggested, adding a minimal `buildpack.toml` to `heroku-buildpack-apt` resolved the initial failure. However, because of other incompatibilities in that buildpack, it just results in other errors. Eventually, the `heroku-buildpack-apt` (or something equivalent) should be transformed into a cloud native version...

**Comment by fagiani** [comment]
Hello @jsamoocha! 

I had a similar requirement and ended up creating a CNB apt-based buildpack off the `heroku-buildpack-apt` called `fagiani/apt`... You can check more details [here](https://github.com/fagiani/apt-buildpack).

Any feedback would be highly appreciated as it is the first buildpack I created pretty much to get a deeper understanding of how it works.

I hope it becomes helpful to others in the future.

**Comment by jsamoocha** [comment]
At the time, I worked around the issue using a totally different approach, not requiring any build packs. So I'm afraid I'm not in the position to provide meaningful feedback on your solution.

**Comment by enricorotundo** [comment]
Hey @fagiani is there any guide out there on how to convert heroku-buildpacks to CNB buildpacks? I see [you've been through this journey as well](https://github.com/heroku/heroku-buildpack-nginx/issues/70#issue-770847901). I'm a bit confused.... isn't heroku supposed to be using the official buildpacks standard?

**Comment by fagiani** [comment]
@enricorotundo There are other versions of buildpacks as you can see below:
![image](https://user-images.githubusercontent.com/2450/151883086-1826739e-50b4-4515-b5d4-3d0c3aa873d3.png)

If I understand it correctly, heroku still uses it's `V2` buildpacks.

I've spent some time to understand how both work in order to transition them to current CNB ones... If you're looking to convert any specific buildpacks and think I can be of help, please feel free to [reach out](https://github.com/fagiani)!

Keep Rocking!
