### ISSUE TITLE
`pack create-package` from buildpack blobs

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#239]
This story should be done on a branch so the community can experiment with it, but not merged until https://github.com/buildpack/rfcs/pull/11 is finalized

## Motivations

Please see https://github.com/buildpack/rfcs/pull/11

## `pack create-package`
**Given** I have the following `package.toml` file
```
[default]
id = "id.buildpack.one"
version = "0.0.1"

[[blobs]]
uri = "https://example.com/buildpack1.tgz"

[[stacks]]
id = "some.stack.id"
```
**And** `https://example.com/buildpack1.tgz` points to an archive with the following entries
```
buildpack.toml
bin
bin/detect
bin/build
```
where `buildpack.toml` has the following contents
```
[buildpack]
id = "id.buildpack.one"
version = "0.0.1"

[[stacks]]
id = "some.stack.id"
```

**When** I run `pack create-package -p <path-to-package.toml> example.com/some/package:tag`
**Then** An image with the tag `example.com/some/package:tag` should be exported to the docker daemon
**And** the package should have a label with key `io.buildpacks.buildpackage.metadata` and the following value
```
{
  "id": "id.buildpack.one",
  "version": "0.0.1",
  "stacks": [
    {
      "id": "some.stack.id",
    }
  ]
}
```
**And** a layer should be created containing `id.buildpack.one` with the following files
```
/cnb/buildpacks/id.buildpack.one/0.0.1/buildpack.toml
/cnb/buildpacks/id.buildpack.one/0.0.1/bin/
/cnb/buildpacks/id.buildpack.one/0.0.1/bin/detect
/cnb/buildpacks/id.buildpack.one/0.0.1/bin/build
```

### --publish
**When** I run `pack create-package -p package.toml example.com/some/package:tag --publish`
**Then** It behaves exactly as above but exports the package to the `example.com` registry

### Notes
* `uri` field should support all `uri` type currently supported by `pack create-builder`
* should use download cache
* multiple buildpack blobs and multiple stacks should be supported

**Comment by jromero** [comment]
@ekcasey  Based on the [spec](https://github.com/buildpack/spec/blob/master/distribution.md#buildpackage) the label should be `io.buildpacks.buildpackage.metadata`

**Comment by ameyer-pivotal** [comment]
This passes acceptance.
