### ISSUE TITLE
`pack create-package` validates default ID and version

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#240]
[PLACEHOLDER]

**Given** a `package.toml` with the following contents
```
[default]
id = "id.buildpack.two"
version = "0.0.2"

[[blobs]]
uri = "https://example.com/buildpack1.tgz"

[[stacks]]
id = "some.stack.id"
```
**Where** `id.buildpack.two` is not a buildpack defined in the `buildpack.toml` in the given blob
**Then** I receive a helpful error message

**Comment by jromero** [comment]
No longer necessary based on changes to `package.toml`
