### ISSUE TITLE
Add version flag support

### ISSUE THREAD

**Issue by josegonzalez** [buildpack/pack#256]
As of pack 0.3.0, we currently have `pack version`, but most tools I know also support `--version` or `-v` flags (some use `-V` because `-v` means verbose...).

```
pack version: v0.3.0 (git sha: 3123e32ea7c570527c6e2cdb31f4e5c002334287)
```

**Comment by ekcasey** [comment]
Thanks for the suggestion @josegonzalez.

In my opinion, we could support both `--version` and `-v` in the case where there is no subcommand. Contributions welcome :)

**Comment by moulikcipherX** [comment]
Is this issue open?

**Comment by jromero** [comment]
Yes. Open to contributions.

**Comment by ktpv** [comment]
-v is now reserved for verbose"in this PR https://github.com/buildpack/pack/pull/314

**Comment by jromero** [comment]
Too eager on the closing of this issue. Apologies.

Personally, I don't have a strong preference on the need a shorthand flag (in our case `-V` would be acceptable) for `--version`. At minimum `--version` makes sense and is somewhat expected.
