### ISSUE TITLE
Add a `report` subcommand

### ISSUE THREAD

**Issue by josegonzalez** [buildpack/pack#257]
For the purposes of filing issues, it should be relatively simple to run a `pack report` to dump out various things about the build environment.

Things it might include

- Version
- Host OS
- How pack was compiled (flags and such)?
- ???

This is incredibly useful in the @dokku project, so I figured it might be useful here too :)

**Comment by jromero** [comment]
Nice suggestion! 

If you expand it past it's current environment, I could see this being extremely helpful for a plethora of inquiries. For example, you could pass a builder image, buildpack, etc. and it could autodetect its type and output relevant information for troubleshooting purposes.

**Comment by jromero** [comment]
## Acceptance

For the first iteration of this command we are going to start with a small subset of information.

### UC1. `pack report`

**When** I run `pack report`
**Then** I'm presented with the following output:
```
Pack:
  Version:  v0.5.0 (git sha: c9cfac75b49609524e1ea33f809c12071406547c)
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.5.0

Config:
  default-builder-image = "some/image"
```

**Comment by ameyer-pivotal** [comment]
This passes acceptance.
