### ISSUE TITLE
Add created-by metadata to builder

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#261]
## Motivation

`pack` has changed it's builder creation process over time. It would be nice for users to know which version of `pack` created a given builder was so that they:

1. know what metadata to expect on the builder
1. know the organizational structure of the image FS (Example: lifecycle binary paths)
1. know whether a builder is compatible to run with another version of `pack`.
1. can provide this information in bug reports involving a custom builder
1. can satisfy their curiosity

### `pack create-builder`

**Given** I have `pack` version `1.2.3`
**When** I run `pack create-builder <builder-image>`
**Then** The `<builder-image>` will have the following information it it's `io.buildpacks.builder.metadata` label
```json
{... "createdBy": {"name": "Pack CLI", "version": "1.2.3"}}}
```

### `pack inspect-builder`
**Given** a builder `<builder-image>` with `createdBy` metadata in the above format
**When** I run `pack inspect-builder <builder-image>`
**Then** I will see the following information in the output
```
$pack inspect-builder <builder-image>
...
Created By: 
  Name: Pack CLI
  Version: 1.2.3
```

**Given** a builder `<builder-image>` w/o `createdBy` in it's metadata
**When** I run `pack inspect-builder <builder-image>`
**Then** `Created By:` will not appear in the output

**Comment by ameyer-pivotal** [comment]
Accepted.
