### ISSUE TITLE
List of cloud native buildpacks in pack CLI

### ISSUE THREAD

**Issue by antonioaguilar** [buildpack/pack#265]
It is not clear from the `pack` cli help or the docs where to get a list of available cloud native buildpacks. Coming from Cloud Foundry, a simple `cf buildpacks` command provides the list of available packs. Is there something equivalent in `pack`?

Trying the following combinations did not work:

```
pack build myapp --buildpack node-engine
pack build myapp --buildpack https://github.com/cloudfoundry/node-engine-cnb
pack build myapp --buildpack https://github.com/cloudfoundry/nodejs-buildpack
```
I can see the list of supported platforms from https://hub.docker.com/r/cloudfoundry/cnb but there are not examples on how to use any of the buildpacks. Adding this information and examples to the `pack` online documentation would improve adoption of the tool, e.g. even some getting started guides for folks coming from CF or Kubernetes.

**Comment by josegonzalez** [comment]
The buildpacks depend on the builder image you are using, but I think it might be cool if we could do something like:

```
# list buildpacks in the builder image
pack buildpack list
```
I think the you can sorta get this via `inspect-builder`, but maybe not in an easily consumable way.

**Comment by antonioaguilar** [comment]
@josegonzalez that's correct, doing a `pack inspect-builder` gave me a list of buildpacks but it was not intuitive at all ... therefore, to use the NodeJS buildpack which is the one I was interested I had to do: 

```
pack build myapp --buildpack org.cloudfoundry.node-engine@latest
```

I would strongly suggest that the `pack` online docs are updated to at least give an example on using the default builder buildpacks, this would be specially useful for folks coming from other platforms.
