### ISSUE TITLE
Add latest symlink to `pack create-builder`

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#27]
__GIVEN__ I have multiple versions of a buildpack
__WHEN__ I update provide "latest=true" for the buildpack in the `buildpacks` list in the builder.toml when i run `pack create-builder`
__THEN__ a relative symlink will be created for the corresponding version and the buildpack marked as latest

**Comment by ekcasey** [comment]
Suggested Acceptance Criteria

**Given** I have created a <builder/image> from the following `builder.toml`
```
[[buildpacks]]
id = "mock.bp.first"
uri = "file://first"

[[buildpacks]]
id = "mock.bp.first"
uri = "file://first-latest"
latest = true

[[buildpacks]]
id = "mock.bp.second"
uri = "file://second"
```
**When** I run `pack build --builder <builder/image> --buildpack mock.bp.first` 
**Then** the buildpack that originally lived in the `first-latest` dir
**And** I see:
> No version for 'mock.bp.first' buildpack provided, will use 'mock.bp.first@latest'
