### ISSUE TITLE
Add support for log levels

### ISSUE THREAD

**Issue by jkutner** [buildpack/pack#271]
The `pack` command should accept an option that determines how verbose the output should be.

This option should also be supported in the various API calls that are used tools that import pack as a dependency.

This will support having things like SHAs logged to debug, or having failed detection output logged to debug while success is logged to info. See: https://github.com/buildpack/pack/issues/126.

This change will require that the log-level be passed on to lifecycle, such that it can do the same thing.

## Option 1: flag per level

Add support for `--debug`, `--verbose`, `--quiet` etc flag for each level.

## Option 2: one option to rule them all

Add a `--log-level <level>` option that accepts the log level desired.

**Comment by jromero** [comment]
@jkutner this issue seems to have been resolved by #314. Is that correct or is there more work to be done?

**Comment by murphybytes** [comment]
@jromero It looks like that is not the case.  #314 added a simple verbose flag.  This issue requires log levels, presumably the standard DEBUG, INFO, WARN, ERROR

**Comment by jkutner** [comment]
I think the `--quiet` and `--verbose` flags are best or a developer facing tool like pack. But the explicit log levels are good for a tool that more internal like lifecycle. I'm going to close this.
