### ISSUE TITLE
.pack/completion: no such file or directory

### ISSUE THREAD

**Issue by suztomo** [buildpack/pack#272]
I tried to run the tutorial but seems there's something missing in completion setup

https://buildpacks.io/docs/install-pack/#auto-completion

```
suztomo@suxtomo24:~$ pack version
v0.3.0 (git sha: 3123e32ea7c570527c6e2cdb31f4e5c002334287)
suztomo@suxtomo24:~$ pack completion
ERROR  open /usr/local/google/home/suztomo/.pack/completion: no such file or directory
```

Am I missing something?

**Comment by jromero** [comment]
@suztomo It seems like PACK_HOME is set to `/usr/local/google/home/suztomo/.pack/` in which I'm assuming that directory doesn't exist. 

This is an oversight in the current implementation as it seems to expect it to already exist. As a workaround you can simply create that directory and try again.

We'll keep this issue open and mark it as a bug. If you'd like to take a swing at a PR it would certainly be appreciated. :D

**Comment by suztomo** [comment]
Yes, I thought the same. I think ”Pack set-default-builder” created the directory later.
(I’m afraid I’m not contributing to a PR for this.)
