### ISSUE TITLE
Docker API Version Too New

### ISSUE THREAD

**Issue by dmcintyre-pivotal** [buildpack/pack#276]
When I run pack I get the following error:

ERROR  Error response from daemon: client version 1.38 is too new. Maximum supported API version is 1.35

Pack version: https://github.com/buildpack/pack/commit/db911eb6818933db223cb18d4085d83e3595bc84

Docker:
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.35
 Go version:        go1.12.7
 Git commit:        74b1e89
 Built:             Fri Jul 26 02:12:11 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          17.12.1-ce
  API version:      1.35 (minimum version 1.12)
  Go version:       go1.9.4
  Git commit:       7390fc6
  Built:            Tue Feb 27 22:20:43 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 Kubernetes:
  Version:          v1.10.0
  StackAPI:         Unknown

I can make pack work by changing the value "1.38" in client.go to "1.35"

**Comment by sclevine** [comment]
Upgrading your Docker daemon will address this issue. We do not support old installations of Docker with API versions less than 1.38.
