### ISSUE TITLE
How to add build arguments?

### ISSUE THREAD

**Issue by saturnism** [buildpack/pack#278]
For some application builds, additional arguments and/or non-default target needs to be called for production build. For example, for JHipster, we need to build with a production profile, e.g. `./mvnw package -Pprod`.

https://github.com/jhipster/generator-jhipster/issues/10255#issuecomment-526937883

**Comment by jkutner** [comment]
Adding an option like `-Pprod` will probably depend on the buildpack in use. The `heroku/java` buildpack uses some env vars, so you can do something like:

```
$ pack build jhipster-app -e MAVEN_CUSTOM_OPTS="-Pprod,heroku -DskipTests" --builder heroku/buildpacks:18 --buildpack heroku/nodejs,heroku/java 
```

**Comment by nebhale** [comment]
Arbitrary build arguments (everything after the resolved gradle or maven executable) can be [set with `BP_BUILD_ARGUMENTS`](https://github.com/cloudfoundry/build-system-cnb/blob/master/README.md#build) on the Cloud Foundry builder.

**Comment by saturnism** [comment]
thanks @nebhale ; i noticed it was committed couple days ago. 😄

**Comment by jromero** [comment]
@saturnism Glad to hear you've got what you needed. 

Closing the issue for now. Feel free to open another if you have further questions.
