### ISSUE TITLE
Allow redirection of stdout when using the pack.Build() API

### ISSUE THREAD

**Issue by scothis** [buildpack/pack#30]
`pack build` produces a lot of meaningful output. When invoking `pack.Build()` via the API instead of the CLI, it's useful to be able to collect this output and redirect/transform it. This is commonly done by the caller passing a logger or an io.Writer to use.

**Comment by sclevine** [comment]
Definitely agree with this. Ideally our API should minimize all interactions with the system (e.g., should take arguments instead of reading env vars as well as the requested feature).

**Comment by dgodd** [comment]
@scothis I think the best way to accomplish this is to deprecate `Build` and have you use the code inside that method https://github.com/buildpack/pack/blob/master/build.go#L178-L194

This means you can then set Stdout, Stderr and Log on the Factory object before calling Run().

@sclevine The only env var read is `HOME` and it is also read during creation of the DefaultBuildFactory, so I think this handles your concern also?

**Comment by sclevine** [comment]
This seems to be exposed via the `Logger` in the latest version of pack. @scothis can we close this issue?
