### ISSUE TITLE
Couldn't find the documentation on `orders`

### ISSUE THREAD

**Issue by dgageot** [buildpack/pack#305]
While creating my builder with `pack create-builder`, I saw this warning:

```
Warning: builder configuration: empty order definition
```

However, I couldn't find any documentation that explains this feature. If such documentation exists or is later on created, it would be nice to point at it in the warning.

**Comment by sclevine** [comment]
Hi @dgageot,

We're right in the middle of shipping a large breaking change in pack. The new builder.toml definition is documented here: https://github.com/buildpack/docs/blob/edge/content/docs/using-pack/working-with-builders.md

This will get merged to master later today, when pack 0.4.0 is cut. Sorry for the trouble.

**Comment by dgageot** [comment]
Thank you very much for the link @sclevine, that would have indeed be useful!
Happy that the doc is part of the release!

**Comment by jromero** [comment]
@dgageot Closing this issue as it seems like the question was answer. Additionally, updated docs have been published.

**Comment by dgageot** [comment]
Awesome!
