### ISSUE TITLE
Update `suggest-stacks` entries

### ISSUE THREAD

**Issue by jromero** [buildpack/pack#311]
We've determined that the cnb bionic stack `io.buildpacks.stacks.bionic` is to be used solely for learning purposes (as a sample and for tutorials) only. Thereby, it should not be suggested via the command `suggest-stacks`.

Related story: #156

**Comment by sclevine** [comment]
This is incorrect -- that stack ID should be suggested. We don't want to suggest `cnbs/build` and `cnbs/run` as locations for that stack ID.

**Comment by jromero** [comment]
My initial impression was that we would remove this entire entry:

```
    Stack ID: io.buildpacks.stacks.bionic
    Description: Minimal Ubuntu 18.04 stack
    Maintainer: Cloud Native Buildpacks
    Build Image: cnbs/build:bionic
    Run Image: cnbs/run:bionic
```

Where does that stack ID come from otherwise?

**Comment by jromero** [comment]
After further discussions with @sclevine and @nebhale we've determined that further adjustments are necessary and that the stack ID `io.buildpacks.stacks.bionic` will still exist but will now be listed under a separate image and maintainer.

Final proposed output:

_Notice:_ 
  _* "Stacks maintained by the Cloud Native Buildpacks project:" section is removed_

```
Stacks maintained by the community:

    Stack ID: heroku-18
    Description: The official Heroku stack based on Ubuntu 18.04
    Maintainer: Heroku
    Build Image: heroku/pack:18-build
    Run Image: heroku/pack:18

    Stack ID: io.buildpacks.stacks.bionic
    Description: A minimal Cloud Foundry stack based on Ubuntu 18.04
    Maintainer: Cloud Foundry
    Build Image: cloudfoundry/build:base-cnb
    Run Image: cloudfoundry/run:base-cnb

    Stack ID: org.cloudfoundry.stacks.cflinuxfs3
    Description: A large Cloud Foundry stack based on Ubuntu 18.04
    Maintainer: Cloud Foundry
    Build Image: cloudfoundry/build:full-cnb
    Run Image: cloudfoundry/run:full-cnb

    Stack ID: org.cloudfoundry.stacks.tiny
    Description: A tiny Cloud Foundry stack based on Ubuntu 18.04, similar to distroless
    Maintainer: Cloud Foundry
    Build Image: cloudfoundry/build:tiny-cnb
    Run Image: cloudfoundry/run:tiny-cnb
```
