### ISSUE TITLE
Build cache should ignore the image tag

### ISSUE THREAD

**Issue by dgageot** [buildpack/pack#319]
**Given** a single project, built with `pack build`,
**When** I build this project twice, with the same base image name but two different tags, `demo/java:v1` and `demo/java:v2`,
**Then** the build cache should not be ignored on the second build.

The cache uses the full image name's sha256 digest as a key. We should at least ignore the tag.

**Comment by ekcasey** [comment]
@dgageot I am not convinced we would want to reuse the cache volume in this situation. It could be useful for some users but very counterproductive in other situations. 

The way the cache is currently implemented it does not grow indefinitely. Rather, unused layers are purged at the end of each build.

If users have, for example, a single repository with multiple tags, where each tag represents a distribution of the same software on a different base OS, none of the cached layers would be reusable between image tags. Each time a different tag was built, the entire cache would be lost.

**Comment by briandealwis** [comment]
Should `pack` also incorporate the builder and stack IDs?  If I switch builders will I have a poisoned cache?

**Comment by ekcasey** [comment]
@briandealwis Layers won't be restored unless the buildpack that generated them (same ID) has detected. I don't think we want to invalidate the cache on a builder change b/c a `pack` user may choose to use a newer builder at a different tag (with updated buildpacks for example) and we still want to restore the cache in that case. 

Stack IDS are a more interesting case. If a layer was originally created for a different stack I agree that it should not be restored. However, I generally think using `pack` to rebuild images with the exact same tag while switching stacks should be avoided. Launch layers may end up getting reused from the previous image even if they are not in the local cache. We could try to guard against all these cases but users should probably just use the `--clear-cache` flag if they are doing something as unexpected as switching stacks.

**Comment by chanseokoh** [comment]
It would still be super useful if there were some way to reuse the cache between different image references, for example, by specifying a cache group or a controlled cache ID. For example, I may tag images according to git commit hashes and also build to different repos based on dev/staging/prod, but whenever a tag is changed, nothing is cached and the build starts from a blank state.

**Comment by dgageot** [comment]
I'm going to close this one. I guess if we want the cache to be reused more often, we should `pack build` with a stable tag (like `:latest`) and tag the image afterwards.
