### ISSUE TITLE
build.go:22:2: cannot find package "github.com/buildpack/packs/img"

### ISSUE THREAD

**Issue by drnic** [buildpack/pack#32]
https://github.com/buildpack/pack/blob/master/build.go#L22 references "github.com/buildpack/packs/img" but https://github.com/buildpack/packs does not have that subfolder. Something I did wrong?

**Comment by sclevine** [comment]
That package moved here: https://github.com/buildpack/lifecycle/tree/master/img

Closing, as it appears to be fixed.
