### ISSUE TITLE
using [[groups]] causes premature failure in detector

### ISSUE THREAD

**Issue by elbandito** [buildpack/pack#321]
I'm currently running Pack CLI version `v0.4.1 (git sha: 90e88e7b1dc02ca65e22548fdfbeabec4c9879a6)`

`builder.toml`:
```
[[groups]]
  buildpacks = [
    { id = "aperolabs/nodejs", version = "v0.1.0" },
    { id = "aperolabs/node-function", version = "0.1.0" },
  ]
```

During `pack create-builder`, I get the following `warnings`:
```
Warning: builder configuration: groups field is obsolete in favor of order
Warning: builder configuration: empty order definition
```

Then when I actually try to run `pack build`, using the builder image from above, I get the following error:
```
Executing lifecycle version 0.4.0
Using build cache volume pack-cache-b5a657e713a9.build
Build cache pack-cache-b5a657e713a9.build cleared
===> DETECTING
[detector] Error: failed to detect: detection failed
ERROR: failed with status code: 6
```

At first, I thought there was something wrong with one of my buildpacks, but after further investigation, I discovered that the culprit is the `[[groups]]` syntax.  If I replace my `builder.toml` file with the following:
```
[[order]]
  [[order.group]]
    id = "aperolabs/nodejs"
    version = "v0.1.0"

  [[order.group]]
    id = "aperolabs/node-function"
    version = "0.1.0"
```

The error message is resolved.

Given the warning messages during `pack create-builder`, I'm under the impression that `[[groups]]`, should still be supported for a short while longer.  Otherwise, I would expect this `warning` to actually be an `error` message.  If the plan is to provide short term backwards compatibility for `[[groups]]` then I believe there is a bug somewhere in the `Pack` CLI or perhaps `Lifecycle` that's causing the mentioned `ERROR: failed with status code: 6`.

**Comment by jromero** [comment]
@elbandito IIRC we've handled this issue via the working group meeting. This issue is a side-effect of the compatibility changes and our choice of words.

> groups field is obsolete in favor of order

means that the `groups` fields aren't being used at all.

I'm closing this for now but feel free to reply if it's still unclear or need to discuss it further. This was definitely a learning opportunity for compatibility changes in the future.
