### ISSUE TITLE
pack build throws away downloaded assets if [builder] stage fails

### ISSUE THREAD

**Issue by drnic** [buildpack/pack#339]
```
$ pack build my-go-thing
...
===> BUILDING
[builder]
[builder] Go Compiler Buildpack 0.0.29
[builder]   Go 1.13: Contributing to layer
[builder]     Downloading from https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz
[builder]     Verifying checksum
[builder]     Expanding to /layers/org.cloudfoundry.go-compiler/go
[builder]
[builder] Go Mod Buildpack 0.0.29
[builder]   : Contributing to layer
[builder] Setting environment variables
[builder] Running `go install`
[builder] go: errors parsing go.mod:
[builder] /workspace/go.mod:5: unknown directive: this
[builder] exit status 1
[builder] Error: failed to build: exit status 103
```

When I run `pack build` again I do not expect, and desperately don't want, it to re-download the expensive/slow go/jdk/ruby runtimes again.

But it does:

```
$ pack build my-go-thing
...
[builder]
[builder] Go Compiler Buildpack 0.0.29
[builder]   Go 1.13: Contributing to layer
[builder]     Downloading from https://buildpacks.cloudfoundry.org/dependencies/go/go1.13.linux-amd64-cflinuxfs3-8b3c3fb8.tar.gz
```

This happens with and without `--publish` flag.

**Comment by sclevine** [comment]
Pack intentionally does not preserve cache layers provided to each buildpack on failure, because the buildpack would need to account for partially-built or invalid cache states. I’d suggest opening an RFC if you feel strongly that this behavior should change.

**Comment by drnic** [comment]
I am prepared to just be an early warning until others come along and complain about the same thing.

**Comment by sclevine** [comment]
Suggestion for an RFC: We could preserve cache layers on a per-buildpack basis, instead of on a per-build basis. Many meta-buildpacks separate supplying dependencies and using them, so this would approximate your ask in a safe way. I would totally support this change.

**Comment by ekcasey** [comment]
This would be complicated to implement given the current spec, but I'm open to the idea that it's worth it if we hear this from multiple sources.

It's also worth noting that this will only help for `cache=true` layers unless we do something different from our normal local caching process here. For example, this will not stop the `org.cloudfoundry.openjdk` buildpack from redownloading the JRE after a fail build (as it is a launch=true, build=false, cache=false layer).
