### ISSUE TITLE
Add `packages` support to `create-package`

### ISSUE THREAD

**Issue by jromero** [buildpack/pack#349]
## Motivation

See [RFC-7](https://github.com/buildpack/rfcs/blob/master/text/0007-spec-distribution.md#buildpack-developer)

### AC1. `create-package` with package in `package.toml`

**Given** I have the following `package.toml` file
```
[default]
id = "buildpack.1"
version = "0.0.1"

[[buildpacks]]
uri = "https://example.com/buildpack1.tgz"

[[packages]]
ref = "package/bp2-bp3"

[[stacks]]
id = "some.stack.id"
```
**And** `https://example.com/buildpack1.tgz` points to an archive with the following entries
```
buildpack.toml
bin
bin/detect
bin/build
```
where `buildpack.toml` has the following contents
```
[buildpack]
id = "buildpack.1"
version = "0.0.1"

[[stacks]]
id = "some.stack.id"
```
**And** there is an image `package/bp2-bp3` created by `pack create-package` with the following `package.toml` contents:

```
[default]
id = "buildpack-2"
version = "0.0.1"

[[buildpacks]]
uri = "buildpack-2-v0.0.1.tgz"

[[buildpacks]]
uri = "buildpack-3-v0.0.1.tgz"

[[stacks]]
id = "some.stack.id"
```
**When** I run `pack create-package -p <path-to-package.toml> example.com/some/package:tag`
**Then** An image with the tag `example.com/some/package:tag` should be exported to the docker daemon
**And** the package should have a label with key `io.buildpacks.buildpackage.metadata` and the following value
```
{
  "id": "buildpack.1",
  "version": "0.0.1",
  "stacks": [
    {
      "id": "some.stack.id",
    }
  ]
}
```
**And** a layer should be created containing `buildpack.1` with the following files:
```
/cnb/buildpacks/buildpack.1/0.0.1/buildpack.toml
/cnb/buildpacks/buildpack.1/0.0.1/bin/
/cnb/buildpacks/buildpack.1/0.0.1/bin/detect
/cnb/buildpacks/buildpack.1/0.0.1/bin/build
```
**And** a layer should be created containing `buildpack.2` with the following files:
```
/cnb/buildpacks/buildpack.2/0.0.1/buildpack.toml
/cnb/buildpacks/buildpack.2/0.0.1/bin/
/cnb/buildpacks/buildpack.2/0.0.1/bin/detect
/cnb/buildpacks/buildpack.2/0.0.1/bin/build
```
**And** a layer should be created containing `buildpack.3` with the following files:
```
/cnb/buildpacks/buildpack.3/0.0.1/buildpack.toml
/cnb/buildpacks/buildpack.3/0.0.1/bin/
/cnb/buildpacks/buildpack.3/0.0.1/bin/detect
/cnb/buildpacks/buildpack.3/0.0.1/bin/build
```

### AC2. nested package must support declared `package.toml` stacks

**Given** I have the following `package.toml` file
```
[default]
id = "buildpack.2"
version = "0.0.1"

[[packages]]
ref = "package/bp2-bp3"

[[stacks]]
id = "some.stack.id.1"

[[stacks]]
id = "some.stack.id.2"

[[stacks]]
id = "some.stack.id.3-missing-from-nested"
```
**And** there is an image `package/bp2-bp3` created by `pack create-package` with the following `package.toml` contents:
```
[default]
id = "buildpack-2"
version = "0.0.1"

[[buildpacks]]
uri = "buildpack-2-v0.0.1.tgz"

[[buildpacks]]
uri = "buildpack-3-v0.0.1.tgz"

[[stacks]]
id = "some.stack.id.1"

[[stacks]]
id = "some.stack.id.2"
```
**When** I run pack create-package -p <path-to-package.toml> example.com/some/package:tag
**Then** I should see an error:
`package 'package/bp2-bp3' does not support stack 'some.stack.id.3-missing-from-nested'`

### Notes
- Should be able to support more than one `[[packages]]` entry and add all corresponding layers to the final builder image.
- `[[packages]]` entry do not require `[[buildpacks]]` entries to be present.
- All `package.toml` stacks must be supported by nested `[[packages]]` and thereby the packaged buildpacks must also support those stacks

**Comment by ameyer-pivotal** [comment]
This passes acceptance. Some minor differences in error message and key names are due to #409.
