### ISSUE TITLE
`pack update-stack` allows a user update an existing stack

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#36]
__WHEN__ I run `pack update-stack my.custom.stack.id --run-image my-org/run --build-image my-org/build`
__THEN__ the stack with the ID my.custom.stack.id will update the existing images for the stack in the config.toml with the ones specified
__AND__ the user will see the following message "\<stack id> successfully updated."

**Notes**
- Multiple run and build images can be provided
- If stack id does not exist - return the following message "\<stack id> does not exist. Please run `pack update-stack` with an existing stack ID."

**Comment by dgodd** [comment]
I have assumed that if either `run-image` or `build-image` is not specified then that entry is unchanged. This means it is NOT possible for a user to set the array for either to empty; this seems reasonable to me (why would you want to do that after all?)

**Comment by ssisil** [comment]
@dgodd - Agreed- seems like a weird edge case to support

**Comment by ssisil** [comment]
@dgodd 

Seeing this error message - 

```
ssisil:bin ssisil$ pack update-stack io.buildpacks.stacks.scott-xenial --build-image ssisil/build:xenial-2 --run-image ssisil/run:xenial-2
Error: Missing stack: stack with id "io.buildpacks.stacks.scott-xenial" not found in pack config.toml
```

Should be this

```
 <stack id> does not exist. Please run pack update-stack with an existing stack ID.
``
