### ISSUE TITLE
Add Default Lifecycle Version to `pack version` output

### ISSUE THREAD

**Issue by ameyer-pivotal** [buildpack/pack#366]
**Given** pack's default lifecycle is hardcoded to `1.2.3`
**When** I run `pack version`
**Then** I see the output:
```
<current pack version string>
Default Lifecycle: 1.2.3
```

**Comment by ameyer-pivotal** [comment]
> I don't think this is appropriate. Personally I think it makes more sense to be part of #257.

That makes sense. This story serves mostly as a placeholder for the general idea, so we can definitely integrate it into #257 if we decide that.

**Comment by jromero** [comment]
@ameyer-pivotal cool. It didn't seem like a placeholder given it has AC as if it were actionable but as you made mention it's still undecided.

**Comment by jromero** [comment]
Incorporated into https://github.com/buildpack/pack/issues/257. See [acceptance](https://github.com/buildpack/pack/issues/257#issuecomment-546185125).
