### ISSUE TITLE
`pack delete-stack` allows a user to remove a custom stack from the config.toml

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#37]
__WHEN__ I run `pack delete-stack my.custom.stack.id`
__THEN__ the stack associated with that ID in the config.toml will be deleted
__AND__ the following message will be displayed to the user 
`my.custom.stack.id has been successfully deleted`

**Notes**
- If the stack ID passed in does not exist, then return the following message `<stack id> does not exist. Please pass in a valid stack ID.`
- If stack ID passed in is set as the default stack, do not delete the stack and return the following message `<stack id> cannot be deleted when it is the default stack. You can change your default stack by running "pack set-default-stack".`

**Comment by dgodd** [comment]
I did not handle the case that a user deletes the default stack. Currently the stack will be deleted and the default stack will still reference it.

**Comment by ssisil** [comment]
@dgodd 

Seeing this message

```
ssisil:bin ssisil$ pack delete-stack io.buildpacks.stacks.scott-xenial
Error: Missing stack: stack with id "io.buildpacks.stacks.scott-xenial" not found in pack config.toml
```

Should be this

```
"io.buildpacks.stacks.scott-xenial" does not exist. Please pass in a valid stack ID.
```
