### ISSUE TITLE
`pack build` returns image SHA on successful build

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#4]
__GIVEN__ I am building an image with pack build
__WHEN__ the build completes successfully
__THEN__ I will see a SHA representing the image returned in the command line in the following format : 

`Image: example.com/myorg/repo@434a7be...`

NOTE: Only do this for `publish`

**Comment by dgodd** [comment]
Do we have a preferred format?

Currently, when publishing, the last line is something similar to the following:
```
2018/08/24 09:16:00 gcr.io/[PROJECTID]/davestest:latest: digest: sha256:1a71cb1fe2e0b8afade8981837cf9d62d79a6b8bd9fcf271b79188e7dbf9df00 size: 2855
```

**Comment by ssisil** [comment]
@dgodd - updated the format in the story
