### ISSUE TITLE
Add `pack version`

### ISSUE THREAD

**Issue by dsyer** [buildpack/pack#43]
It's nice to know what you are running,

**Comment by nebhale** [comment]
Agreed.  Tags if tagged, commit if not.

**Comment by dgodd** [comment]
@ssisil We will need to double check version next time we do a release.

**Comment by dsyer** [comment]
Looks like this didn't work as expected (with 0.0.5 I expect to see "VERSION: 0.0.5"):

```
$ pack version
VERSION: (git sha: 4e05716058bf4bac98386fe2724024ebda0a99e3)
```
