### ISSUE TITLE
create builder fails with image not found when it exists

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#44]
default-stack-id = "io.buildpacks.stacks.scott-trusty"

[[stacks]]
  id = "io.buildpacks.stacks.scott-trusty"
  build-images = ["ssisil/build:trusty2"]
  run-images = ["ssisil/run:trusty2"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
  build-images = ["cfbuildpacks/cflinuxfs3-cnb-experimental:build"]
  run-images = ["cfbuildpacks/cflinuxfs3-cnb-experimental:run"]

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
  build-images = ["packs/build"]
  run-images = ["packs/run"]

**Comment by dgodd** [comment]
Sadly things just worked on my machine. Did I do anything different to you @ssisil  ?

```
$  pack create-builder newnpmcnb3 -b ./builder.toml
2018/10/10 08:18:16 Pulling builder base image  cfbuildpacks/cflinuxfs3-cnb-experimental:build

$  docker run -it newnpmcnb3 bash

#  find /buildpacks/
/buildpacks/
/buildpacks/order.toml
/buildpacks/org.cloudfoundry.buildpacks.npm
/buildpacks/org.cloudfoundry.buildpacks.npm/2.3.4
/buildpacks/org.cloudfoundry.buildpacks.npm/2.3.4/buildpack.toml
/buildpacks/org.cloudfoundry.buildpacks.npm/2.3.4/bin
/buildpacks/org.cloudfoundry.buildpacks.npm/2.3.4/bin/build
/buildpacks/org.cloudfoundry.buildpacks.npm/2.3.4/bin/detect
/buildpacks/org.cloudfoundry.buildpacks.nodejs
/buildpacks/org.cloudfoundry.buildpacks.nodejs/1.6.32
/buildpacks/org.cloudfoundry.buildpacks.nodejs/1.6.32/buildpack.toml
/buildpacks/org.cloudfoundry.buildpacks.nodejs/1.6.32/bin
/buildpacks/org.cloudfoundry.buildpacks.nodejs/1.6.32/bin/build
/buildpacks/org.cloudfoundry.buildpacks.nodejs/1.6.32/bin/detect

# cat /buildpacks/order.toml
[[groups]]

[[groups.buildpacks]]
id = "org.cloudfoundry.buildpacks.nodejs"
version = "1.6.32"

[[groups.buildpacks]]
id = "org.cloudfoundry.buildpacks.npm"
version = "2.3.4"
```


Contents of builder.toml

```
[[buildpacks]]
id = "org.cloudfoundry.buildpacks.nodejs"
uri = "file://nodejs"

[[buildpacks]]
id = "org.cloudfoundry.buildpacks.npm"
uri = "file://npm"

[[groups]]
buildpacks = [
  { id = "org.cloudfoundry.buildpacks.nodejs", version = "1.6.32" },
  { id = "org.cloudfoundry.buildpacks.npm", version = "2.3.4" },
]

```

**Comment by dgodd** [comment]
I tried setting the id incorrectly inside the builder.toml `buildpacks` section, but that gave me an error

I then tried setting the id incorrectly inside groups/buildpacks ; that gave me a builder image with the buildpack in it, and an order.toml with the incorrect id. Thus this image would have failed to work at build time, but did copy the buildpack in (which I believe is the first thing that failed for you Scott)./

Thus I am still unsure

**Comment by ssisil** [comment]
Let me re-test and see if I am still getting this. Its weird that I didnt see this error initially and then all of a sudden started seeing it. Makes me think something is wrong on my end

**Comment by ssisil** [comment]
@dgodd - F
