### ISSUE TITLE
Support (remote) references to buildpack archives in builder.toml

### ISSUE THREAD

**Issue by ericbottard** [buildpack/pack#46]
When creating a builder via `pack create-builder -b builder.toml`, the `builder.toml` currently has to reference each involved buildpack with a path that needs to exist on the local filesystem (`file://`). This is cumbersome and hinders the ability to distribute the sources for a builder (you don't want to put each buildpack binary in source control)

**Comment by ssisil** [comment]
@ericbottard - Im assuming you will just add support for `https://` in addition to `file://`. Let me know if you are thinking about this in a different way

**Comment by ericbottard** [comment]
This is correct. 

In the process, this will change the semantics of `file://` to correctly parse that scheme: `file://buildpacks/some/path` is *not* a relative path of the file kind to `buildpacks/some/path`. In that example, `buildpacks` is a host and `/some/path` is a (absolute) path. `file:///this/is/an/absolute/path` is possible. To continue using paths, just drop the `file://` protocol.

**Comment by sclevine** [comment]
Merged in #57.
