### ISSUE TITLE
Go client api on pack cli for riff cli consumption

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#5]
__GIVEN__ I am a developer creating a CLI that will leverage Cloud  Native Buildpacks
__WHEN__ I integrate with the `pack build` command
__THEN__ I will use the Go Client API to include that functionality in my CLI

**Comment by dgodd** [comment]
@scothis we have just shipped the change we forecasted above. From master you should now be able to use

```
pack.Build(appDir, detectImage, repoName string, publish bool) error
```

I don't think I clarified publish last time. `publish` controls whether or not images are read/written to the local daemon or a registry (publish=true meaning registry)
