### ISSUE TITLE
In a stack that doesn't have the pack user `pack build` fails to export

### ISSUE THREAD

**Issue by dsyer** [buildpack/pack#50]
```
*** EXPORTING:
Step 1/3 : FROM cfbuildpacks/cflinuxfs3-cnb-experimental:run
---> 2b15b1dbf8f9
Step 2/3 : ADD --chown=pack:pack /workspace/app /workspace/app
Error: image build: unable to convert uid/gid chown string to host mapping: can't find uid for user pack: no such user: pack
Usage:
```

**Comment by ekcasey** [comment]
I am going to change it to use the `$PACK_USER_ID` and `$PACK_USER_GID` env vars to determine the user and group. Those variables will need to be set on the stack images if they aren't already.

**Comment by nebhale** [comment]
@ekcasey You should open an issue in the stack specification for this and link it back to here.

**Comment by dsyer** [comment]
There is a `org.cloudfoundry.stacks.cflinuxfs3` stack that I have been trying to use and it doesn't have those env vars (I have to add them using a manual docker build - thanks @dgodd for the tip). Whoever is maintaining that should get the message as well (I have no idea).

**Comment by ekcasey** [comment]
https://github.com/buildpack/spec/issues/16

**Comment by dsyer** [comment]
I can't make comments on that tracker. Can someone ask then to add `yj` (seems like it is in `packs/build`)?

**Comment by sclevine** [comment]
I can prioritize a story to get `yj` added to it.

I'm worried about the CNB version of cflinuxfs3 diverging from the CF production version of cflinuxfs3, but I think it's reasonable to include it for simple shell script CNBs, given the TOML parsing requirements.
