### ISSUE TITLE
Contract of "stack" is unclear

### ISSUE THREAD

**Issue by dsyer** [buildpack/pack#53]
I get that it is an abstraction, and abstractions have some value, but this one feels too opaque to me. I can copy-paste stack IDs around in my `buildpack.tomls` but I don't really understand what they are. I gather, by changing them, that they kind of represent a base image. There's probably more to it than that, or else why not just call it "base image"? It might be good to know what the image is though, so I can have a look inside it and figure out if my buildpack is ever going to run on it.

**Comment by sclevine** [comment]
The concept of a "stack" is defined here: https://github.com/buildpack/spec/blob/master/platform.md#stacks

A stack is a combination of a build-time base image and a runtime base image. We can't just use the tag names of those though, because they may live in different registries (including private registries), and it's important that the run image live in the registry that you're publishing to.

**Comment by nebhale** [comment]
Spec aside, do we have more humane documentation about what stacks are, scheduled in the backlog somewhere?

**Comment by ekcasey** [comment]
@nebhale we recently scheduled work on the `buildpack/pack` README. I think that should help. If we explain the `pack *-stack` commands and the `-s` flag for `pack create-builder` it should be more obvious what a stack is and how it is used.

**Comment by nebhale** [comment]
Sounds good.

**Comment by dsyer** [comment]
>  We can't just use the tag names of those though, because they may live in different registries (including private registries), and it's important that the run image live in the registry that you're publishing to.

That information is really important. Please include it in some humane documentation, along with some examples of how to actually discover/define the image labels for a given stack.

**Comment by sclevine** [comment]
We definitely plan to have detailed, plain-english documentation for the pack CLI ready before we cut the first beta.

As @ekcasey mentions, the stack image tags are stored/manipulated with the `pack *-stack` commands. This will be covered in the documentation for those commands.

**Comment by jromero** [comment]
@dsyer @nebhale we recently added additional human readable documentation around stacks. 

https://buildpacks.io/docs/using-pack/stacks/

Does that satisfy this issue or do we feel more is necessary?

Feedback would be appreciated.

**Comment by jromero** [comment]
Closing due to staleness and provided documentation mentioned above.
