### ISSUE TITLE
Provide a way to populate `<platform>/env`

### ISSUE THREAD

**Issue by nebhale** [buildpack/pack#66]
The buildpack spec describes the way that environment variables get to buildpacks during build is [by populating `<platform>/env`](https://github.com/buildpack/spec/blob/master/buildpack.md#provided-by-the-platform).  There is also a proposal to [extend this to detect](https://github.com/buildpack/spec/issues/24).

Currently there is no way to populate this part of the filesystem during `pack build` and there should be.

**Comment by ericbottard** [comment]
I assume you mean "during `pack build`"?

**Comment by ekcasey** [comment]
This is available using `pack build --env-file` as of `pack@v0.0.6`
