### ISSUE TITLE
Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by timfpark** [buildpack/pack#67]
I'm trying to build a node.js service using pack and I'm running into an issue where it seems like the builder container does not have python in the path.  Here is what I am seeing:

```
$ pack build location-service:1001 --path myNodeJSServiceRoot
2018/11/07 16:58:52 Pulling builder image 'packs/samples' (use --no-pull flag to skip this step)
2018/11/07 16:58:53 Selected run image 'packs/run' from stack 'io.buildpacks.stacks.bionic'
2018/11/07 16:58:53 Pulling run image 'packs/run' (use --no-pull flag to skip this step)
*** DETECTING:
2018/11/07 23:59:02 Group: Sample Node.js Buildpack: pass
*** ANALYZING: Reading information from previous image for possible re-use
2018/11/07 16:59:03 WARNING: skipping analyze, image not found
*** BUILDING:

> snappy@6.0.4 install /workspace/app/node_modules/snappy
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Linux 4.9.93-linuxkit-aufs
gyp ERR! command "/cache/io.buildpacks.samples.nodejs/nodejs/bin/node" "/cache/io.buildpacks.samples.nodejs/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /cache/io.buildpacks.samples.nodejs/node_modules/snappy
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snappy@6.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@6.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pack/.npm/_logs/2018-11-07T23_59_07_886Z-debug.log
2018/11/07 23:59:07 Error: failed to : exit status 1
Error: failed with status code: 7
```

**Comment by ekcasey** [comment]
@timfpark You are correct, `python` is not on the `builder`'s path. 

 If your build requires `python`, you will need a python buildpack to contribute a build layer that supplies a `python` executable subsequent buildpacks.

Right now the `pack` default builder (`pack/samples`) does not come with a `python` buildpack (it only contains a few simple example buildpack). As far as I am aware, nobody has yet written a v3 `python` buildpack. We hope to have one available in coming months.

**Comment by sclevine** [comment]
Note that if you’re looking for a version of Python maintained with LTS by an OS vendor (e.g., what you get with `apt-get install python`) you could modify the default stack’s run and build images (and then setup CI to keep them updated).

This should be much easier in future versions of pack, when support for mixins is introduced (https://github.com/buildpack/spec/pull/18).

**Comment by timfpark** [comment]
Ok - thank you - I will use the workaround you mentioned.

I think for the node.js buildpack you should strongly consider adding python by default because there are many node modules that use node-gyp that will need it (like snappy above):  https://github.com/nodejs/node-gyp

**Comment by ekcasey** [comment]
I am going to close this issue given that we have removed the nodejs sample buildpack. The larger ecosystem of productionalized buildpacks that now exists should provide solutions to this issue. Feel free to open an issue with the buildpack authors if you have further issues.
