### ISSUE TITLE
pack create-builder silently omits a buildpack whose version does not match the manifest

### ISSUE THREAD

**Issue by ericbottard** [buildpack/pack#77]
given 

```
[[buildpacks]]
id = "com.acme"
uri = "https://some.storage.com/my-buildpack.tgz"  # or possibly a "-latest.tgz" form of URI

...

[[groups]]

  [[groups.buildpacks]]
  id = "com.acme"
  version = "1.0.0"
```

if what's found at that URI does not have a BP with version == 1.0.0, the buildpack is just silently omitted from the group! This is absolutely crazy, as it obviously leads to runtime errors way down the line, while this should be caught way earlier. This is bound to happen because builders and buildpacks are often managed in different repositories.

**Comment by ericbottard** [comment]
refs #58

**Comment by ekcasey** [comment]
@ericbottard yeah this is definitely less than ideal behavior. I think the bigger problem is in `detector` not `create-builder`. During detection, if a group (manually provided or from `order.toml`) references a buildpack that is not available, is is simply skipped without causing an error.

For example, the following will succeed right now.
```
pack build test/app -p <path/to/node/app> --buildpack=no-exist@bad-version  --buildpack=io.buildpacks.samples.nodejs@latest
```

If `detector` errors on missing buildpacks, then although `create-builder` may succeed in your example, you would quickly realize the error when using the buildpack. The `order.toml` would reference a missing buildpack and detection would fail.

Fixing `detector` is near the top of our backlog. I could see value in adding additional validation during `create-builder` but it doesn't feel as high priority as the `detector` changes to me.

**Comment by ekcasey** [comment]
this is now fixed in `detector` in the previous release of lifecycle and in `master` of `pack`
