### ISSUE TITLE
Invalid built image with newest stack

### ISSUE THREAD

**Issue by ericbottard** [buildpack/pack#79]
Doing the following:
```
cd /tmp
git clone https://github.com/projectriff-samples/node-square
cd node-square
touch riff.toml
pack build --builder projectriff/builder  -p .  --publish <your/image:here>
```
(ie building a riff function that is written in node)
with a recent `pack` version leads to the following when trying to run the built app:
```
docker run -p8080:8080 <your/image:here>
2018/12/13 11:01:24 Error: failed to launch: modify env: find buildpack directory: stat /workspace/org.cloudfoundry.openjdk: no such file or directory
```

The openjdk BP passed detection (it's a no-op) but did not contribute anything in the build phase in this case (it's a node function).

I managed to "cure" the problem by reverting to pack@0.0.4 **AND** removing the `~/.pack/config.toml` file, so I suspect this has something to do with the changes in the default stack

**Comment by ekcasey** [comment]
hey @ericbottard this issue is fixed by https://github.com/buildpack/lifecycle/pull/47. `pack`@`v0.0.8` should be fixed as soon as we publish new `packs/*:v3alpha2` images (hopefully today).

**Comment by ericbottard** [comment]
👍

**Comment by ekcasey** [comment]
Images are published. This issue should be resolved. Let us know if you run into any more problems!
