### ISSUE TITLE
Prevent pack from logging cli flags

### ISSUE THREAD

**Issue by matthewmcnew** [buildpack/pack#84]
Prevent logging pack cli flags in output to prevent consumers like riff from seeing messages about irrelevant flags. For example we log the --no-pull flag in Build.

**Acceptance Criteria**
**When** I import the pack CLI's non-`main` packages as a library from outside of the module
**And** I execute any methods in the exported interface of those packages
**Then** I do not observe any CLI-related messages, including in returned `error`s.

**Comment by sclevine** [comment]
Added AC.

**Comment by djoyahoy** [comment]
@sclevine after our refactor, I'm not sure this issue is necessary anymore. I took a cursory glance over the public interface and I don't see anything that stands out. I'd recommend closing this and awaiting feedback from users of our newly exported client interface.

**Comment by mgibson1121** [comment]
Based on @djoyahoy's comment, not sure if this ticket was actually worked on.  But, tested by running `no-pull` with a `pack build` and didn't see `no-pull` in the output.  So I'm going to accept.

**Comment by ekcasey** [comment]
fixed on `master`, will ship in `v0.2.0`
