### ISSUE TITLE
--buildpack flag non-existant?  --builder issue?

### ISSUE THREAD

**Issue by dylanz** [buildpack/pack#88]
I'm trying to point to a specific buildpack using the --buildpack flag (which is in the docs: https://cl.ly/a01f3a0dc9dc, and I see it in build.go#buildCommandFlags) but getting an error that the flag doesn't exist:

> pack build packs/test --path /var/tmp/test--buildpack buildpacks/ruby-buildpack
> Error: unknown flag: --buildpack

When this failed I tried to create my own builder using create-builder.  It successfully created (I see it locally as an image), but trying to build using it returns an error:

> pack build packs/test --path /var/tmp/test --builder ruby-buildpack:latest
> ... pull access denied for ruby-buildpack, repository does not exist or may require 'docker login'

**Comment by ekcasey** [comment]
@dylanz 

What version of `pack` are you using?

1. The `--buildpack` flag has exists and support either a buildpack ID or a path to a directory. It looks like an update to the help text adds incorrect information. I just filed a bug to fix it https://github.com/buildpack/pack/issues/89

2. If your newly created builder only exists locally you need to run `pack build` with the `--no-pull` flag. Otherwise `pack` will automatically try to fetch update and fail if the builder does not exist remotely. We will likely change this behavior to be more permissive in the near future (i.e. always attempt to pull but continue without failing if it doesn't exist).

**Comment by dylanz** [comment]
@ekcasey (thanks for your help here!)

I'm not sure exactly what version I'm using (what's the best way to check, and, should I maybe add an enhancement issue to add a --version flag?)

1. I was running it with the added space (I copy/pasted incorrectly)

2. Awesome... thanks for creating that issue!

3. I'll definitely try this with the --no-pull option

I noticed in the README that there's no "Installing Pack" section.  What's the correct way to install pack at the moment?

**Comment by ekcasey** [comment]
`pack version` should print the version for you

The releases page has information on how to install https://github.com/buildpack/pack/releases. Currently the way to install is simply download the `tar`, extract the `pack` binary and copy it into your `PATH`. At some point we hope to provide distribution through some popular package managers.

**Comment by dylanz** [comment]
Perfect.  I'm now on v0.0.9 (master)

I created a builder successfully using the following command:
```
> pack create-builder ruby-buildpack:latest -b builder.toml
```

The builder.toml being
```
[[buildpacks]]
  id = "ruby-buildpack"
  uri = "./buildpacks/ruby-buildpack"
```

Running build using this new builder fails detection for some reason.  Here's the command:
```
> pack build test-project --builder ruby-buildpack:latest -p /var/tmp/test-project --no-pull

Using user-provided builder image ruby-buildpack:latest
Selected run image packs/run:v3alpha2 from stack io.buildpacks.stacks.bionic
Using cache volume pack-cache-1e5d3c8073e2736fa56640c4e9085d8a
===> DETECTING
[detector] 2019/01/24 21:14:25 Error: failed to detect
ERROR: run detect container: failed with status code: 6
```

The "ruby-buildpack" I'm referencing is basically just cloudfoundry/ruby-buildpack, but I added a buildpack.toml in its root so it would be picked up by pack:

```
[buildpack]
name = "Ruby"
id = "ruby-buildpack"
version = "0.0.1"
```

If I run detect on my project directly using the ruby-buildpack, it does work correctly:
```
> buildpacks/ruby-buildpack/bin/detect /var/tmp/test-project
ruby 1.7.31
```

**Comment by ekcasey** [comment]
@dylanz currently `pack` only works with v3 buildpacks. I do not believe there is a working v3 cloudfoundry ruby buildpack yet. 

It will be here https://github.com/cloudfoundry/ruby-cnb, but it looks like there is only one commit so far. The pattern for finding cloudfoundry v3 buildpacks in github is https://github.com/cloudfoundry/<language>-cnb.

Maybe @hone can tell us if there is a v3 heroku buildpack that you can demo.

With the next version of `pack` we will providing an easy way to discover and use tested builder images (starting with cf and heroku builders as they are the most mature).

**Comment by ekcasey** [comment]
also, are you still having issues with the `--buildpack` flag? I wasn't able to recreate your issue using the v0.0.9 released binary

**Comment by dylanz** [comment]
@ekcasey Ahhh... that all definitely makes sense.  Thanks for shooting those links over, that's extremely helpful.  In regard to the --buildpack flag, I haven't had a chance to use it yet but will definitely update this when I do.

**Comment by ekcasey** [comment]
@dylanz I am going to assume I can close this, but please feel free to reopen if your issue isn't fixed!
