### ISSUE TITLE
pack build --buildpack flag has incorrect help text

### ISSUE THREAD

**Issue by ekcasey** [buildpack/pack#89]
The current help text states
```
Generate app image from source code

Usage:
  pack build <image-name> [flags]

Flags:
      --builder string      Builder (defaults to builder configured by 'set-default-builder')
      --buildpack strings   Buildpack ID, path to directory, or path/URL to .tgz file
                            Repeat for each buildpack in order,
                              or supply once by comma-separated list
...
```

However, only a Buildpack ID or a path to a directory are currently supported

**Comment by djoyahoy** [comment]
Fixed in commit b11b12c7e54da840763a0e02376b1563d2c2b09d

**Comment by djoyahoy** [comment]
Re-opening this issue because we have not yet cut a release with this fix.

**Comment by mgibson1121** [comment]
Validated that  ```path/URL to .tgz file``` is removed from the pack build help text

**Comment by ameyer-pivotal** [comment]
@mgibson1121 @sclevine  We should keep documentation in mind as part of acceptance, as it looks like we're missing an update in README.md. Will fix.
