### ISSUE TITLE
Show image pull progress

### ISSUE THREAD

**Issue by scothis** [buildpack/pack#91]
When pack pulls images it provides no output to the user to indicate progress. Many builder images are large (riff is ~600MB, and growing), for users with slow network connections, it can appear that the build has stalled.

Minimally, a note can be added saying this may take a while. A better approach is to mimic the output that `docker pull` provides.

**Comment by sclevine** [comment]
Already prioritized for the next release here: https://github.com/buildpack/roadmap/issues/41 😄

**Comment by ekcasey** [comment]
this is done in `v0.1.0`
