### ISSUE TITLE
Stack flag for "pack build"

### ISSUE THREAD

**Issue by kardolus** [buildpack/pack#92]
It's not straight forward for us to build an OCI image for a non-bionic stack. It would be great if the build command had a `--stack` flag on the build command so we could easily build an image for cflinuxfs3.

**Comment by sclevine** [comment]
Can you provide more details about your use case? `pack build` has a `--builder` flag that accomplishes this already (by selecting a builder that contains the stack), and we don't intend to support building without a builder.

**Comment by kardolus** [comment]
Spend about 20 minutes with @djoyahoy last week trying to build an OCI image for cflinuxfs3. We ended up giving up and used an integration test with dagger to test our app on fs3. 

We discussed during retro that it would be great if a flag could be added to pack. If that is not possible we can create some script ourselves and add it to the buildpack workstations.

**Comment by sclevine** [comment]
@kardolus, I'm not suggesting that it isn't possible, just that I don't understand the request.

What does "an image for cflinuxfs3" mean? Is that an app image, a builder image, or something else? What are you trying to accomplish, and why would this flag be useful?

**Comment by kardolus** [comment]
I'm trying to build my app on cflinuxfs3 instead of on bionic because I require gcc during the build phase. Went through the following steps:

Create a builder.toml file
```
buildpacks = [{id = "<from buildpack.toml>",uri = "file://<from ./scripts/package.sh>", latest = true}]

[[groups]]
buildpacks = [{id = "<from buildpack.toml>", version = "latest"}]
```

```
# packs/run:v3alpha2 = bionic
./scripts/package.sh
.bin/pack add-stack cflinuxfs3 --run-image=packs/run:v3alpha2 --build-image=cloudfoundry/cflinuxfs3 
.bin/pack create-builder cnb-pack-builder -b builder.toml -s cflinuxfs3
.bin/pack build rustapp --builder cnb-pack-builder --path integration/testdata/simple_app --no-pull
```

This resulted in 
```
Error: invalid builder image "cnb-pack-builder": missing required label "io.buildpacks.stack.id"
```

**Comment by nebhale** [comment]
The point of a stack is that it's made up of a build and run image.  They are encapsulated _in_ a stack.

**Comment by sclevine** [comment]
`cloudfoundry/cflinuxfs3` is not a valid build image. The CNB concept of a stack is not the same as Cloud Foundry's concept of a stack. Let's chat about this over zoom.

**Comment by sclasen** [comment]
Just hit a case where I would like this too.

When authoring a buildpack, I created a stack using the heroku docker images, and then want to iterate on the buildpack by doing `pack build --buildpack . --path ../path/to/test/app --stack my-stack`

Once the buildpack works, Id likely create a builder for it, using the stack and the buildpack, but at development time it seems like having a --stack in build would be a nice to have.

Whats the alternative workflow here for developing buildpacks?

**Comment by kinkerl** [comment]
@sclasen the Docker image you are using needs to be build with a label, something like `LABEL io.buildpacks.stack.id="somelabel"`

**Comment by jromero** [comment]
It appears that this issue was resolved via support.

There are multiple reasons why this should be closed:
1. [`stack`](https://buildpacks.io/docs/concepts/components/stack/) is a composition of two images, a `run-image` and a `build-image`
2. Unclear use case, `--builder` satisfies described workflow.
3. We now [fail](https://github.com/buildpack/pack/blob/3b65cd774105a5f6e4487e67cef1f44a062b6d5a/internal/builder/builder.go#L99) when `io.buildpacks.stack.id` label is not present when creating a builder catching the error before `pack build`


If this feature is still requested please create a new issue with a use case in mind.
